#!/bin/sh
#
#//////////////////////////////////////////////////////////////////////////
#    Copyright Webtrobat Team 2013
#    This file is part of Webtrobat.
#
#    Webtrobat is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Webtrobat is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Webtrobat.  If not, see <http://www.gnu.org/licenses/>.
#////////////////////////////////////////////////////////////////////////

FILE_NAME="${1}"
FIRST_LINE=`head -n 1 "${FILE_NAME}"`

echo "${FIRST_LINE}" | \
    grep -E '^\[(none|(D|U)[0-9]+)\](\[[0-9]+\]|\[Refactor\])? \(([A-Z][A-Z],?)+\) .*'
RESULT=$?
if [ "$RESULT" -eq "1" ]; then
    echo "=============================="
    echo "Commit message is in wrong format, supported is:"
    echo "[TaskNumber] (EG*, GE*)"
    echo "[TaskNumber][Refactor] (EG*, GE*)"
    echo "[TaskNumber][IssueNumber] (EG*, GE*)"
    echo "e.g. '[D10] (MF)'"
    echo "After the first line the commit should also include a descriptive message."
    echo "=============================="

    exit 1
fi
